# Generated by Django 3.0.7 on 2020-06-14 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0004_auto_20200614_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 14, 5, 27, 41, 150321)),
        ),
    ]
