state_choices = {
    'AL': 'Alabama',
'AK': 'Alaska',
'AZ': 'Arizona',
'AR': 'Arkansas',
'CA': 'California',
'CO': 'Colorado',
'CT': 'Connecticut',
'DE': 'Delaware',
'DC': 'DistrictOfColumbia',
'FL': 'Florida',
'GA': 'Georgia',
'HI': 'Hawaii',
'ID': 'Idaho',
'IL': 'Illinois',
'IN': 'Indiana',
'IA': 'Iowa',
'KS': 'Kansas',
'KY': 'Kentucky',
'LA': 'Louisiana',
'ME': 'Maine',
'MD': 'Maryland',
'MA': 'Massachusetts',
'MI': 'Michigan',
'MN': 'Minnesota',
'MS': 'Mississippi',
'MO': 'Missouri',
'MT': 'Montana',
'NE': 'Nebraska',
'NV': 'Nevada',
'NH': 'NewHampshire',
'NJ': 'NewJersey',
'NM': 'NewMexico',
'NY': 'NewYork',
'NC': 'NorthCarolina',
'ND': 'NorthDakota',
'OH': 'Ohio',
'OK': 'Oklahoma',
'OR': 'Oregon',
'PA': 'Pennsylvania',
'RI': 'RhodeIsland',
'SC': 'SouthCarolina',
'SD': 'SouthDakota',
'TN': 'Tennessee',
'TX': 'Texas',
'UT': 'Utah',
'VT': 'Vermont',
'VA': 'Virginia',
'WA': 'Washington',
'WV': 'WestVirginia',
'WI': 'Wisconsin',
'WY': 'Wyoming'
}

price_choices = {
    '100000': '$1,00,000',
    '200000': '$2,00,000',
    '300000': '$3,00,000',
    '400000': '$4,00,000',
    '500000': '$5,00,000',
    '600000': '$6,00,000',
    '700000': '$7,00,000',
    '800000': '$8,00,000',
    '900000': '$9,00,000',
    '1000000': '$1M+',
}

bedroom_choices = {
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7': 7,
    '8': 8,
    '9': 9,
    '10': 10,
}